version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/fitcompanion
      - MONGO_URI=mongodb://mongo:27017/my-fit-companion
      - JWT_SECRET=your-production-jwt-secret
      - ALLOWED_ORIGINS=https://yourapp.com
    depends_on:
      - db
      - mongo
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped
    
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fitcompanion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
      
  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: my-fit-companion
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
      
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - uploads:/usr/share/nginx/html/uploads:ro
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data:
  mongo_data:
  uploads:
